FROM ubuntu:latest

# set environment vars
ENV HADOOP_HOME /opt/hadoop
ENV JARs opt/hadoop/share/hadoop/tools/lib/hadoop-streaming-3.3.6.jar
ENV HDFS_NAMENODE_USER="root"
ENV HDFS_DATANODE_USER="root"
ENV HDFS_SECONDARYNAMENODE_USER="root"
ENV YARN_RESOURCEMANAGER_USER="root"
ENV YARN_NODEMANAGER_USER="root"
# install packages
RUN \
  apt-get update && apt-get install -y \
  ssh \
  rsync \
  vim;

# Install OpenJDK-8
RUN apt-get update && \
    apt-get install -y openjdk-8-jdk && \
    apt-get install -y ant && \
    apt-get clean;

# Fix certificate issues
RUN apt-get update && \
    apt-get install ca-certificates-java && \
    apt-get clean && \
    update-ca-certificates -f;

# Setup JAVA_HOME -- useful for docker commandline
ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64/
RUN export JAVA_HOME

# download and extract hadoop, set JAVA_HOME in hadoop-env.sh, update path
RUN \
  wget https://downloads.apache.org/hadoop/common/stable/hadoop-3.3.6.tar.gz && \
  tar -xzvf hadoop-3.3.6.tar.gz

RUN  mv hadoop-3.3.6 /opt/hadoop
RUN  echo "export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64" >> /opt/hadoop/etc/hadoop/hadoop-env.sh
RUN  echo "PATH=$PATH:/opt/hadoop/bin" >> ~/.bashrc

# create ssh keys
RUN \
  ssh-keygen -t rsa -P '' -f ~/.ssh/id_rsa && \
  cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys && \
  chmod 0600 ~/.ssh/authorized_keys

# copy hadoop configs
ADD config/*xml /opt/hadoop/etc/hadoop/

# copy ssh config
ADD config/ssh_config /root/.ssh/config

# copy script to start hadoop
ADD config/start-hadoop.sh start-hadoop.sh

# RUN wget https://repository.cloudera.com/artifactory/cloudera-repos/org/apache/hadoop/hadoop-streaming/2.6.0-cdh5.16.1.1/hadoop-streaming-2.6.0-cdh5.16.1.1.jar &&
# expose various ports
# EXPOSE 8088 50070 50075 50030 50060
